Задание 2
mipt-diht/mipt-latex-fall2018-magnitov pull request #3
Opened 2018-10-27 16:14 UTC by magnitov

2018-10-30 15:38 UTC, AShepelevv requested changes

2018-10-30 15:38 UTC, AShepelevv commented on task2.1.tex
> +            Случайный вектор $\vec \xi \sim \mathcal{N}(m,\Sigma)$ --- гауссовский, если его характеристическая функция $\varphi_{\xi}(\vec t) = \exp{(i(\vec m, \vec t) - \frac{1}{2}(\Sigma \vec t, \
Используется `\frac` внутри скобок, а скобки по высоте меньше дроби, грустно...
Не забывайте о `\left` и `\right`.

2018-10-30 15:38 UTC, AShepelevv commented on task2.1.tex
> +            Случайный вектор $\vec \xi \sim \mathcal{N}(m,\Sigma)$ --- гауссовский, если его характеристическая функция $\varphi_{\xi}(\vec t) = \exp{(i(\vec m, \vec t) - \frac{1}{2}(\Sigma \vec t, \
Используйте `\vec{t}`, чтобы стрелочка не залазила на скобку.

2018-10-30 15:38 UTC, AShepelevv commented on task2.1.tex
> +            Случайный вектор $\vec \xi$ --- гауссовский, если он представляется в следующем виде: $\vec \xi = A \vec \eta + \vec b$, где $\vec b \in \mathbb{R}^n$, $A \in \mat{(m \times n)}$ и $\eta
Перед тире ставится неразрывный пробел.

2018-10-30 15:45 UTC, AShepelevv requested changes

2018-10-30 15:45 UTC, AShepelevv commented on task2.2.tex
> +            Предположим, что за пределами солнечного круга кривая вращения Галактики плоская, параметр плато $v$ = 240 км/с. Пусть известно, что диск нейтрального водорода простирается до галактоцент
Зачем `=240` выносить из формулы?

Наименование пишется через неразрывный пробел, например, `$v = 240$~км/с`.

2018-10-30 15:45 UTC, AShepelevv commented on task2.2.tex
> +            В какой момент по истинному солнечному времени 1 сентября Регул ($\alpha_1 = 10^h9^m, \delta_1 = 11^{\circ}53^{'}$) и Шератан ($\alpha_2 = 11^h15^m, \delta_2 = 15^{\circ}20^{'}$) находятс
Угловые минуты пишутся без степени, то есть Просто `20'`.
Между градусами и минутами и между минутами и секундами ставится половинный пробел.
`h`, `m`, `s` – наименования, то есть текст. Значит и писать тх нужно внутри `\text{}`.

2018-10-30 15:45 UTC, AShepelevv commented on task2.2.tex
> +            Предположим, что за пределами солнечного круга кривая вращения Галактики плоская, параметр плато $v$ = 240 км/с. Пусть известно, что диск нейтрального водорода простирается до галактоцент
`$R_{max}$`
`max` – индекс, а, значит, текст. Используйте `\text{}`

2018-10-30 15:45 UTC, AShepelevv commented on task2.2.tex
> +            Оцените долю темной материи внутри скопления, если масса межгалактического газа на порядок превышает массу галактик, а типичные скорости галактик в скоплении составляют 1000 км/с. Размер
После тире ставится пробел. Заодно оно не будет с минусом сливаться.

2018-10-30 15:45 UTC, AShepelevv commented on task2.2.tex
> +            В некотором скоплении галактик содержится 70 спиральных и 30 элиптических галактик. Известно, что абсолютная звездная величина эллиптических галактик равна $-20$, соотношение масса-светим
Наименования пишутся через неразрывный пробел. `210~км/с`.

2018-10-30 15:45 UTC, AShepelevv commented on task2.2.tex
> +            Оцените долю темной материи внутри скопления, если масса межгалактического газа на порядок превышает массу галактик, а типичные скорости галактик в скоплении составляют 1000 км/с. Размер
Наименования

2018-10-30 15:45 UTC, AShepelevv commented on task2.2.tex
> +            Лупа и Пупа живут на антипланетах, обращающихся вокруг звезды с массой $M_* \simeq 10 M_{\odot}$ по эллиптической орбите с фокальным параметром $p = 0.3$ а.е. и эксцентриситетом $e = 0.72
Наименования.

а. е. нужно писать через половинный пробел.

2018-10-30 15:47 UTC, AShepelevv commented
@magnitov Объедините все в один файл, пожалуйста.

2018-10-30 20:48 UTC, magnitov commented on task2.1.tex
> +            Случайный вектор $\vec \xi \sim \mathcal{N}(m,\Sigma)$ --- гауссовский, если его характеристическая функция $\varphi_{\xi}(\vec t) = \exp{(i(\vec m, \vec t) - \frac{1}{2}(\Sigma \vec t, \
Стрелочка все равно залазит, даже при таком использовании

2018-10-30 20:49 UTC, magnitov commented on task2.1.tex
> +            Случайный вектор $\vec \xi \sim \mathcal{N}(m,\Sigma)$ --- гауссовский, если его характеристическая функция $\varphi_{\xi}(\vec t) = \exp{(i(\vec m, \vec t) - \frac{1}{2}(\Sigma \vec t, \
Дробь же не внутри скобок, зачем делать одну скобку большую, а рядом маленькую? По-моему в рамках данного текста все нормально смотрится

2018-11-04 17:33 UTC, AShepelevv commented on task2.1.tex
> +            Случайный вектор $\vec \xi \sim \mathcal{N}(m,\Sigma)$ --- гауссовский, если его характеристическая функция $\varphi_{\xi}(\vec t) = \exp{(i(\vec m, \vec t) - \frac{1}{2}(\Sigma \vec t, \
https://tex.stackexchange.com/questions/176165/vector-arrow-running-into-brackets

2018-11-05 06:09 UTC, magnitov commented on task2.1.tex
> +            Случайный вектор $\vec \xi \sim \mathcal{N}(m,\Sigma)$ --- гауссовский, если его характеристическая функция $\varphi_{\xi}(\vec t) = \exp{(i(\vec m, \vec t) - \frac{1}{2}(\Sigma \vec t, \
Вроде все правки пофиксил, посмотри как сможешь

2018-11-05 07:26 UTC, merged